comment style consistent and update permission cmd
Make comment style consistent with other and make PERMISSION_COMMAND part more elegant

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -23,20 +23,20 @@ STEPS="${*:-install before home root after}" # Default order of steps
 install_packages() {
 	printf '\n\033[1;7;34m%s\033[0m\n' 'Install packages'
 
-	## Arch Linux: Add keyring and mirrolis to be able to install packages from 'chaotic-aur' 
-	# $Pacman_COMMAND git base-devel
-	# git clone 'https://aur.archlinux.org/chaotic-keyring.git' "$TEMPORARY/chaotic-keyring"
-	# cd "$TEMPORARY/chaotic-keyring" || exit 1
-	# makepkg --noconfirm
-	# $PERMISSION_COMMAND pacman --noconfirm --needed --upgrade chaotic-keyring-*.zst 
-	# git clone 'https://aur.archlinux.org/chaotic-mirrorlist.git' "$TEMPORARY/chaotic-mirrorlist"
-	# cd "$TEMPORARY/chaotic-mirrorlist" || exit 1
-	# makepkg --noconfirm
-	# $PERMISSION_COMMAND pacman --noconfirm --needed --upgrade chaotic-mirrorlist-*.zst   
-	# cd "$WD" || exit 1
-	# $PERMISSION_COMMAND sh -c "echo \"\" >> /etc/pacman.conf"  # for Arco Linux
-	# $PERMISSION_COMMAND sh -c "echo \"[chaotic-aur]\" >> /etc/pacman.conf"
-	# $PERMISSION_COMMAND sh -c "echo \"Include = /etc/pacman.d/chaotic-mirrorlist\" >> /etc/pacman.conf"
+	# Arch Linux: Add keyring and mirrolis to be able to install packages from 'chaotic-aur' 
+	#$Pacman_COMMAND git base-devel
+	#git clone 'https://aur.archlinux.org/chaotic-keyring.git' "$TEMPORARY/chaotic-keyring"
+	#cd "$TEMPORARY/chaotic-keyring" || exit 1
+	#makepkg --noconfirm
+	#$PERMISSION_COMMAND pacman --noconfirm --needed --upgrade chaotic-keyring-*.zst 
+	#git clone 'https://aur.archlinux.org/chaotic-mirrorlist.git' "$TEMPORARY/chaotic-mirrorlist"
+	#cd "$TEMPORARY/chaotic-mirrorlist" || exit 1
+	#makepkg --noconfirm
+	#$PERMISSION_COMMAND pacman --noconfirm --needed --upgrade chaotic-mirrorlist-*.zst   
+	#cd "$WD" || exit 1
+
+	# For Arco Linux
+	#$PERMISSION_COMMAND sh -c "printf '\n[chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist' >> /etc/pacman.conf"
 
 	superbbootstrap_install_packages "$DOTFILES_PATH/packageslist" # you can change packageslist's path here
 
@@ -105,14 +105,6 @@ after_symlink() {
 # Don't touch anything from this point to the end of file
 # if you don't know what you are doing.
 
-if [ -x "$(command -v sudo)" ]; then
-	PERMISSION_COMMAND='sudo'
-elif [ -x "$(command -v doas)" ]; then
-	PERMISSION_COMMAND='doas'
-elif [ "$PACKAGEMANAGER_MAIN" != 'Termux' ]; then
-	printf '\n\033[1;7;31m%s\033[0m\n' "Permission command not found or unsupported"
-	exit 1
-fi
 
 # Values
 WD="$PWD"
@@ -121,6 +113,17 @@ TMPDIR="${TMPDIR:-/tmp}"
 TEMPORARY="$TMPDIR/superb-bootstrap"
 
 DOTFILES_PATH=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
+
+if [ -x "$(command -v sudo)" ]; then
+	PERMISSION_COMMAND='sudo'
+elif [ -x "$(command -v doas)" ]; then
+	PERMISSION_COMMAND='doas'
+elif [ -x "$(command -v termux-setup-storage)" ]; then
+	PACKAGEMANAGER_MAIN='Termux'
+else
+	printf '\n\033[1;7;31m%s\033[0m\n' "Permission command not found or unsupported"
+	exit 1
+fi
 
      APT_MARK='APT';      APT_PM='apt'         ;      APT_COMMAND="$PERMISSION_COMMAND $APT_PM install --assume-yes"
   Mports_MARK='MPT';   Mports_PM='mports'      ;   Mports_COMMAND="$PERMISSION_COMMAND $Mports_PM install"
@@ -141,28 +144,26 @@ MacPorts_MARK='MCP'; MacPorts_PM='port'        ; MacPorts_COMMAND="$PERMISSION_C
      SBO_MARK='SBO';      SBO_PM='sbopkg'      ;      SBO_COMMAND="$PERMISSION_COMMAND $SBO_PM -ifq"
     Snap_MARK='SNA';     Snap_PM='snap'        ;     Snap_COMMAND="$PERMISSION_COMMAND $Snap_PM install"
 
-case $(uname -s | tr '[:upper:]' '[:lower:]') in
-	'darwin'*)
-		PACKAGEMANAGER_LIST='Homebrew MacPorts MAS'
-	;;
-	'freebsd'*)
-		PACKAGEMANAGER_MAIN='PKGNG'
-	;;
-	'midnightbsd'*)
-		PACKAGEMANAGER_MAIN='Mports'
-	;;
-	'netbsd'*)
-		PACKAGEMANAGER_MAIN='PKGIN'
-	;;
-	'openbsd'*)
-		PACKAGEMANAGER_MAIN='OpenBSD'
-	;;
-	*)
-		if [ -x "$(eval "command -v \"termux-setup-storage\"")" ]; then
-			PACKAGEMANAGER_MAIN='Termux'
-		else
+if [ -z "$PACKAGEMANAGER_MAIN" ]; then
+	case $(uname -s | tr '[:upper:]' '[:lower:]') in
+		'darwin'*)
+			PACKAGEMANAGER_LIST='Homebrew MacPorts MAS'
+		;;
+		'freebsd'*)
+			PACKAGEMANAGER_MAIN='PKGNG'
+		;;
+		'midnightbsd'*)
+			PACKAGEMANAGER_MAIN='Mports'
+		;;
+		'netbsd'*)
+			PACKAGEMANAGER_MAIN='PKGIN'
+		;;
+		'openbsd'*)
+			PACKAGEMANAGER_MAIN='OpenBSD'
+		;;
+		*)
 			for packagemanager_check in 'APT' 'Pacman' 'Portage' 'Slackpkg' 'XBPS' 'Zypper'; do
-				[ -x "$(eval "command -v \"\$${packagemanager_check}_PM\"")" ] && {
+				[ -x "$(eval command -v \$${packagemanager_check}_PM)" ] && {
 					PACKAGEMANAGER_MAIN="$packagemanager_check"
 					break
 				}
@@ -176,9 +177,9 @@ case $(uname -s | tr '[:upper:]' '[:lower:]') in
 			if [ "$PACKAGEMANAGER_MAIN" = 'APT' ] || [ "$PACKAGEMANAGER_MAIN" = 'Pacman' ]; then
 				PACKAGEMANAGER_LIST="$PACKAGEMANAGER_LIST Snap"
 			fi
-		fi
-	;;
-esac
+		;;
+	esac
+fi
 
 PACKAGEMANAGER_LIST="$PACKAGEMANAGER_MAIN $PACKAGEMANAGER_LIST" # This is a list of package managers supported on bootstrapping OS
 
